# Configuration file for Arrikto Rok JupyterHub Spawner UI
# Each key corresponds to JupyterHub Rok Spawner UI option

# The structure of this file is very similar with the one of the default
# Spawner UI configuration, available at:
#
# kubeflow/jupyter/ui/default/config.yaml

spawnerFormDefaults:
  rokLabURL:
    # The URL of a Jupyter Lab, already snapshotted in Rok
    value: ''
  image:
    value: qingcloud/tensorflow-notebook-cpu:1.12.0
    options:
      - qingcloud/tensorflow-notebook-cpu:1.12.0
  cpu:
    value: '1.0'
  memory:
    value: 1.0Gi
  workspaceVolume:
    value:
      type:
        value: New
      rokURL:
        value: ''
      name:
        value: {username}{servername}-workspace
      size:
        value: '10'
      mountPath:
        readOnly: true
        value: /home/jovyan
  dataVolumes:
    value: []
  extraResources:
    value: "{{}}"
